### ISSUE TITLE
run.sh bug

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/plannable#38]
by examining the code, cd "$(dirname "$0")" on run.sh. this line:

"$(dirname "$0")" echos to /bin on my computer which does not exist under scripts/

it has no effect on the bash file.

**Comment by OAHC2022** [comment]
"$(dirname "$0")"  works fine now under bash. But cannot cd to the directory.

**Comment by hanzhi713** [comment]
It was suspected that it is the problem of Chao's Hardware :)

**Comment by hanzhi713** [comment]
Run.sh is now replaced by `npm run data` (59d3deedf146e9369299518ca4fcf993ef5f0421) to improve compatibility on other operating systems.
