### ISSUE TITLE
Feature request: searching classrooms

### ISSUE THREAD

**Issue by dw61** [awesome-schedule/plannable#44]
@OAHC2022 and I just happened to enter Rice 032 this evening and was curious what class is going on. It would be great if I could search `Rice032` and have a list of classes that meet in that room.

**Comment by hanzhi713** [comment]
Sure. It should be easy to implement this feature.

**Comment by hanzhi713** [comment]
Implementation should be complete by now. You can access this feature from a development deployment of plannable: https://dev.plannable.org/. Please note that room search is not available in fuzzy search. It might be added later if I have time. 

If there are no issues, I will merge changes to master later, which will update the production website.

**Comment by dw61** [comment]
Looks good. However it seems that I need to include the full name of the building, i.e. `rice hall 130`, `mechanical engr bldg 341` instead of `rice130` or `mechanical341`. Is that something fixable?

**Comment by hanzhi713** [comment]
Yes, if the fuzzy search is used. The quick search uses nothing more than string.indexOf, while fuzzy search uses tokenization with trigram similarity. Give me some time and I will add it to the fuzzy search tab.

**Comment by dw61** [comment]
OK, nice!

**Comment by hanzhi713** [comment]
The fuzzy search is now rewritten to support better room search. You should be able to use the fuzzy search tab on https://dev.plannable.org/ to search for rooms. However, to obtain the best results, you need to specify that you are searching specifically for rooms by querying like `:room mechanical341` or `:room rice 130`. 

If you're curious about that have changed, you can checkout this diff: https://github.com/awesome-schedule/plannable/compare/new_fuzzy?expand=1. Searcher.cpp is the file that implements the fuzzy search, and FastSearcher.ts is a wrapper around it.

**Comment by dw61** [comment]
That's interesting. I tried to search for `:room mechanical341` on https://dev.plannable.org but nothing shows up. I attached screenshot below.

<img width="274" alt="Screen Shot 2021-09-08 at 15 16 23" src="https://user-images.githubusercontent.com/27620726/132571287-ccd03c3d-3447-468d-85ee-0cbadaf50a69.png">
<img width="276" alt="Screen Shot 2021-09-08 at 15 16 29" src="https://user-images.githubusercontent.com/27620726/132571289-c84d9e8f-91f2-4cb4-87da-1351112caf0d.png">

**Comment by dw61** [comment]
I see. You have to go to the fuzzy tab at the left. Thanks!

**Comment by hanzhi713** [comment]
Plannable v9.5.0 https://github.com/awesome-schedule/plannable/releases/tag/v9.5.0 now includes this feature. Issue closed.
